// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC48PWO1P3377RPOeZfiLivh1r3a-RSIaY',
    appId: '1:238325657962:web:be89785fd9642dd2c0f513',
    messagingSenderId: '238325657962',
    projectId: 'mynotes-4a9b9',
    authDomain: 'mynotes-4a9b9.firebaseapp.com',
    storageBucket: 'mynotes-4a9b9.appspot.com',
    measurementId: 'G-MR58KMWP8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-rIUS6gJEzcA4JIydI7xpFmMi-EARTEQ',
    appId: '1:238325657962:android:93342fd48ccaf7bdc0f513',
    messagingSenderId: '238325657962',
    projectId: 'mynotes-4a9b9',
    storageBucket: 'mynotes-4a9b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDatFXqInT2ZCbx5bI827XV1SvRujjS610',
    appId: '1:238325657962:ios:53a8575f82077f62c0f513',
    messagingSenderId: '238325657962',
    projectId: 'mynotes-4a9b9',
    storageBucket: 'mynotes-4a9b9.appspot.com',
    iosClientId: '238325657962-apqqldjs8jidvag2hnkgb3npjet4p33k.apps.googleusercontent.com',
    iosBundleId: 'com.project33.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDatFXqInT2ZCbx5bI827XV1SvRujjS610',
    appId: '1:238325657962:ios:40321de3dad05558c0f513',
    messagingSenderId: '238325657962',
    projectId: 'mynotes-4a9b9',
    storageBucket: 'mynotes-4a9b9.appspot.com',
    iosClientId: '238325657962-7k1jtkn2jef89557kiot3hfef049flrr.apps.googleusercontent.com',
    iosBundleId: 'com.project33.mynotes.RunnerTests',
  );
}
